apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6
    helm:
      values: |
        global:
          image:
            tag: v2.9.3
        
        configs:
          params:
            server.insecure: true
          cm:
            url: https://argocd.platform.local
            dex.config: |
              connectors:
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: $github-oauth:clientId
                    clientSecret: $github-oauth:clientSecret
                    orgs:
                    - name: your-org
        
        server:
          extraArgs:
            - --insecure
          service:
            type: LoadBalancer
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - argocd.platform.local
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.platform.local
        
        controller:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        
        dex:
          enabled: true
        
        redis:
          enabled: true
        
        repoServer:
          replicas: 2
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
