apiVersion: v2
name: microservice
description: A Helm chart for deploying microservices on the platform
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - microservice
  - platform
  - kubernetes

home: https://github.com/nataliagranato/plataform-engineer
sources:
  - https://github.com/nataliagranato/plataform-engineer

maintainers:
  - name: Platform Team
    email: platform@company.com

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
