{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.microservice.securityContext | nindent 12 }}
          image: {{ include "microservice.image" . }}
          imagePullPolicy: {{ .Values.microservice.image.pullPolicy }}
          
          ports:
            {{- range .Values.microservice.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          
          {{- if .Values.microservice.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.microservice.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          
          {{- if .Values.microservice.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.microservice.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.microservice.resources | nindent 12 }}
          
          env:
            {{- range .Values.microservice.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            
            {{- if or .Values.postgresql.enabled .Values.externalDatabase.enabled }}
            - name: DATABASE_URL
              {{- if .Values.externalDatabase.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.existingSecretPasswordKey | default "database-url" }}
              {{- else }}
              value: {{ include "microservice.databaseURL" . | quote }}
              {{- end }}
            {{- end }}
            
            {{- if or .Values.redis.enabled .Values.externalCache.enabled }}
            - name: REDIS_URL
              {{- if .Values.externalCache.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalCache.existingSecret }}
                  key: {{ .Values.externalCache.existingSecretPasswordKey | default "redis-url" }}
              {{- else }}
              value: {{ include "microservice.redisURL" . | quote }}
              {{- end }}
            {{- end }}
          
          {{- with .Values.microservice.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.microservice.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      
      {{- with .Values.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.microservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.microservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.microservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
